# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"

run:
  timeout: 5m

linters:
  default: standard
  disable:
    - depguard

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    # Ignore long lines in generated files
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - goconst
    # Ignore error return value in tests
    - path: _test\.go
      text: "Error return value"
      linters:
        - errcheck
