# https://taskfile.dev

version: '3'

vars:
  APP_NAME: razd
  VERSION:
    sh: cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version'

tasks:
  default:
    desc: "Start development (build + test)"
    cmds:
      - task: build
      - task: test

  setup:
    desc: "Setup project dependencies"
    cmds:
      - echo "Installing Rust dependencies..."
      - cargo fetch
      - echo "✓ Dependencies installed"

  build:
    desc: "Build the project"
    cmds:
      - echo "Building {{.APP_NAME}}..."
      - cargo build
      - echo "✓ Build completed"

  test:
    desc: "Run all tests"
    cmds:
      - echo "Running tests..."
      - cargo test
      - echo "✓ All tests passed"

  run:
    desc: "Run razd CLI (usage: task run -- --help)"
    cmds:
      - cargo run -- {{.CLI_ARGS}}


  clean:
    desc: "Clean build artifacts"
    cmds:
      - cargo clean
      - echo "✓ Cleaned build artifacts"
